config/routes.rb
ShoeApp::Application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy] do
    get :guest
  end


  namespace :api, defaults: { format: :json } do
    resources :projects, except: [:new, :edit] do
      member do
        get :followers
        get :funders
      end
    end

    resources :updates, only: [:create, :show]
    resources :comments, only: [:create]
    resources :project_fundings, only: [:create]
    resources :project_followings, only: [:create]
    resources :users, only: [:show, :update]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                         :integer          not null, primary key
#  name                       :string(255)      not null
#  email                      :string(255)      not null
#  password_digest            :string(255)      not null
#  session_token              :string(255)      not null
#  location                   :string(255)
#  biography                  :text
#  website                    :text
#  created_at                 :datetime
#  updated_at                 :datetime
#  profile_photo_file_name    :string(255)
#  profile_photo_content_type :string(255)
#  profile_photo_file_size    :integer
#  profile_photo_updated_at   :datetime
#

class User < ActiveRecord::Base
  validates :name, :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :ensure_session_token

  has_attached_file :profile_photo, :styles => {
    :big => "600x600>",
    :medium => "300x300>",
    :small => "30x30#",
    :profile => "50x50#"
  },
  :default_url => "https://s3-us-west-2.amazonaws.com/shoeappdev/default.png"

  validates_attachment_content_type(
    :profile_photo,
    :content_type => /\Aimage\/.*\Z/
  )

  has_many :started_projects, class_name: "Project", foreign_key: :founder_id
  has_many :project_followings, class_name: "ProjectFollowing",
            foreign_key: :follower_id
  has_many :followed_projects, through: :project_followings,
            source: :project
  has_many :project_backings, class_name: "ProjectFunding",
            foreign_key: :funder_id
  has_many :backed_projects, through: :project_backings, source: :project
  has_many :comments, class_name: "Comment", foreign_key: :author_id

  def self.find_by_credentials(credentials)
    user = User.find_by_email(credentials[:email])
    return nil if user.nil?
    return user if user.is_password?(credentials[:password])
    return nil
  end

  def password=(secret)
    @password = secret
    self.password_digest = BCrypt::Password.create(secret)
  end

  def is_password?(secret)
    BCrypt::Password.new(self.password_digest).is_password?(secret)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  attr_reader :password

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    before_action :require_signed_in, only: [:show, :backed_projects,
      :started_projects, :followed_projects]
    before_action :restrict_profile_settings, only: [:update]
    wrap_parameters :user, include: [:profile_photo, :name, :biography, :location, :website]


    def show
      @user = User.includes(:backed_projects, :started_projects, :followed_projects).find(current_user.id)
      render :show
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_profile_params)
        render :show
      else
        render json: @user.errors.full_messages, status: :unprocessable_entity
      end
    end

    private
    def user_profile_params
      params.require(:user).permit(:name, :biography, :location,
        :website, :profile_photo
      )
    end


    def restrict_profile_settings
      redirect_to root_url unless (current_user.id == params[:id].to_i)
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/views/users/edit.html.erb
<div class="container container-fluid">
  <div class="row">
    <div class="col-xs-5 col-xs-offset-2">
      <h1>Edit Profile</h1>
      <form action="<%= user_url(current_user)%>" method="post" role="form">
        <input type="hidden" name="_method" value="PATCH">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <div class="form-group">
          <input type="file" name="project[profile_photo]" id="photo"
                 class="form-control">
        </div>

        <div class="form-group">
          <input type="text"
                 name="user[name]"
                 id="name"
                 value="<%= current_user.name %>"
                 class="form-control"
                 palceholder="Name"><br>
        </div>

        <div class="form-group">
          <textarea name="user[biography]"
                    id="bio"
                    placeholder="We suggest a short bio"
                    class="form-control">
          </textarea><br>

        </div>

        <div class="form-group">
          <input type="text"
                 name="user[location]"
                 id="location"
                 palceholder="San Francisco, CA"
                 class="form-control"><br>
        </div>

        <div class="form-group">
          <input type="text"
                 name="user[website]"
                 id="website"
                 palceholder="www.example.com"
                 class="form-control"><br>

        </div>

        <input type="submit" value="Save Settings" class="btn btn-primary">


      </form>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container container-fluid full-width bg">
  <div class="row full-width mrlr">
    <div class="col-xs-4 col-xs-offset-2 sign-ins form-border">
      <h2 class="sign-in-header">Sign up</h2>
      <form action="/users" method="post" form="role">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <div class="form-group no-margin">
          <label for="name"></label>
          <input type="text"
                 name="user[name]"
                 id="name"
                 class="form-control",
                 placeholder="Name">
        </div>
        <div class="form-group no-margin">
          <label for="email"></label>
          <input type="text"
                 name="user[email]"
                 id="email"
                 class="form-control",
                 placeholder="Email">
        </div>
        <div class="form-group">
          <label for="password"></label>
          <input type="password"
                 name="user[password]"
                 id="password"
                 class="form-control",
                 placeholder="Password">
        </div>

          <input type="submit" value="Sign up" class="btn btn-primary mrtb">
      </form>
    </div>
  </div>
</div>