config/routes.rb
ShoeApp::Application.routes.draw do
  root to: 'static_pages#root'

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy] do
    get :guest
  end


  namespace :api, defaults: { format: :json } do
    resources :projects, except: [:new, :edit] do
      member do
        get :followers
        get :funders
      end
    end

    resources :updates, only: [:create, :show]
    resources :comments, only: [:create]
    resources :project_fundings, only: [:create]
    resources :project_followings, only: [:create]
    resources :users, only: [:show, :update]
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav nav-pills nav-links no-margin col">
        <li><%= link_to image_tag("/assets/kickoff.png", size: "115x20"), root_url, class: "no-margin pl1 col", style: "padding-top: 23px"%></li>
        <li><%= link_to "Discover", root_url, class: "block px1 py2 grey-dark h5 bold" %></li>
        <li><%= link_to "Start", "#/projects/new", class: "block px1 py2 grey-dark h5 bold" %></li>
      </ul>
</div>




    <% if signed_in? %>
    <div class="dropdown pull-right no-margin col block profile-dropdown">
      <button class="btn btn-default dropdown-toggle profile-button"
              type="button"
              id="dropdownMenu1"
              data-toggle="dropdown">
              <% if (signed_in?)%>
                <%= image_tag @current_user.profile_photo(:small) %>
                <span class="caret"></span>
              <% else %>
                <span class="glyphicon glyphicon-user"></span>
              <% end %>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Profile", "#/profile", tabindex: "-1"%></li>
        <li><%= link_to "Edit Settings", "#/profile/edit",
          tabindex: "-1"%></li>
        <li><%= link_to "Sign out",
              session_url,
              method: :delete, tabindex: "-1", class: "signout" %></li>
      </ul>
    </div>

    <% else %>
    <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav no-margin">
      <li><%= link_to "Guest", guest_session_url, class: "block h5 bold px1 py2" %></li>
      <li><%= link_to "Log in", new_session_url, class: "block h5 bold px1 py2" %></li>
      <li><%= link_to "Sign up", new_user_url, class: "block h5 bold px1 py2" %></li>
    </ul>
    <% end %>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dimissible" role="alert">
  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;
  </span><span class="sr-only">Close</span></button>
  <%= flash[:errors].join("<br>").html_safe %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kickoff</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: "layouts/header" %>
<%= yield %>

<div class="footer">
</div>
<%= javascript_include_tag 'application' %>
</body>
</html>